---
# tasks file for vscode
  - name: Get systemd default target
    ansible.builtin.command:
      "systemctl get-default"
    changed_when: false
    register: systemdefault

  - name: Ensure vscode repository is added
    ansible.builtin.yum_repository:
      name: code
      description: 'microsoft vscode repo'
      baseurl: "{{ burl }}"
      enabled: true
      gpgcheck: true
      gpgkey: "{{ gkey }}"
    when:
      - "'graphical' in systemdefault.stdout"
      - ansible_os_family == "RedHat"

  - name: Import vscode repository key
    ansible.builtin.rpm_key:
      state: present
      key: "{{ gkey }}"
    when: ansible_os_family == "RedHat"

  - name: Install vscode software
    when:
      - "'graphical' in systemdefault.stdout"
      - ansible_os_family == "RedHat"
    ansible.builtin.dnf:
      name: code
      state: present
