---
# tasks file for edge
  - name: Get systemd default target
    ansible.builtin.command:
      "systemctl get-default"
    changed_when: false
    register: systemdefault

  - name: Ensure edge repository is added
    ansible.builtin.yum_repository:
      name: microsoft-edge 
      description: 'microsoft edge repo'
      baseurl: "{{ burl }}"
      enabled: true
      gpgcheck: true
      gpgkey: "{{ gkey }}"
    when:
      - "'graphical' in systemdefault.stdout"
      - ansible_os_family == "RedHat"

  - name: Import edge repository key
    ansible.builtin.rpm_key:
      state: present
      key: "{{ gkey }}"
    when: ansible_os_family == "RedHat"

  - name: Install edge software
    when:
      - "'graphical' in systemdefault.stdout"
      -  ansible_os_family == "RedHat"
    ansible.builtin.dnf:
      name: microsoft-edge-stable 
      state: present
