galaxy_info:
  author: neil docherty 
  description: install microsoft vscode for rhel 8&9 systems 
  company: Univeristy College London 


  min_ansible_version: 2.1


  platforms:
    - name: RHEL
      versions:
        - 8
        - 9

  galaxy_tags:
    - vscode
    - editor
    - text
    - microsoft
